spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - security-local
        - common
      prod:
        - db-prod
        - security-prod
        - common
    include:
      - db
      - security

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    com: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: trace

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com: info